export interface AiRepo {
  id: number;
  name: string;
  full_name: string;
  owner: string;
  description: string;
  stars: number;
  forks: number;
  language: string;
  category: string;
  topics: string[];
  updated_at: string;
  readme: string;
}

export const AI_REPOS: AiRepo[] = [
  // ── AI Agents & Frameworks ──
  { id: 1, name: "langchain", full_name: "langchain-ai/langchain", owner: "langchain-ai", description: "Building applications with LLMs through composability. The most popular framework for LLM app development.", stars: 108000, forks: 17000, language: "Python", category: "ai-agents", topics: ["llm", "agents", "langchain", "framework"], updated_at: "2026-07-10T12:00:00Z", readme: "## LangChain\n\nBuilding applications with LLMs through composability.\n\n### Core Features\n\n- **LCEL** — LangChain Expression Language\n- **Agents** — ReAct, OpenAI Functions, Custom\n- **Chains** — Composable building blocks\n- **Memory** — Conversation, Buffer, Summary\n- **Callbacks** — Logging, tracing, monitoring\n\n### Quick Start\n\n```bash\npip install langchain\n```\n\n### Integrations\n\nOpenAI, Anthropic, Google, Hugging Face, 100+ more" },
  { id: 2, name: "AutoGPT", full_name: "Significant-Gravitas/AutoGPT", owner: "Significant-Gravitas", description: "AutoGPT is a platform for building and running autonomous AI agents in your browser.", stars: 172000, forks: 45000, language: "Python", category: "ai-agents", topics: ["autonomous-agents", "ai", "gpt", "automation"], updated_at: "2026-07-11T08:00:00Z", readme: "## AutoGPT\n\nAutoGPT is a platform for building and running autonomous AI agents.\n\n### Features\n\n- **Autonomous Agents** — Set goals and let AI complete them\n- **Web Browsing** — Agents can search and browse\n- **Code Execution** — Write and run code\n- **File Management** — Read/write files and databases\n\n### Quick Start\n\n```bash\ngit clone https://github.com/Significant-Gravitas/AutoGPT.git\ncd AutoGPT\n./run.sh\n```" },
  { id: 3, name: "CrewAI", full_name: "crewAIInc/crewAI", owner: "crewAIInc", description: "Framework for orchestrating role-playing, autonomous AI agents. Build multi-agent systems.", stars: 28000, forks: 3800, language: "Python", category: "ai-agents", topics: ["agents", "multi-agent", "orchestration", "framework"], updated_at: "2026-07-09T10:00:00Z", readme: "## CrewAI\n\nFramework for orchestrating role-playing, autonomous AI agents.\n\n### Key Concepts\n\n- **Crew** — Team of agents working together\n- **Agent** — Autonomous unit with defined role\n- **Task** — Specific assignment for an agent\n- **Process** — Workflow execution strategy\n\n### Quick Start\n\n```bash\npip install crewai\n```" },
  { id: 4, name: "haystack", full_name: "deepset-ai/haystack", owner: "deepset-ai", description: "LLM orchestration framework to build customizable, production-ready LLM applications.", stars: 18500, forks: 3000, language: "Python", category: "ai-agents", topics: ["llm", "rag", "search", "pipelines"], updated_at: "2026-07-08T14:00:00Z", readme: "## Haystack\n\nLLM orchestration framework by deepset.\n\n### Features\n\n- **RAG Pipelines** — Retrieve-Augment-Generate\n- **Document Stores** — Elasticsearch, Weaviate, Pinecone\n- **Agents** — Tool-using, conversational\n- **Evaluation** — Metrics and testing\n\n### Quick Start\n\n```bash\npip install haystack-ai\n```" },
  { id: 5, name: "pydantic-ai", full_name: "pydantic/pydantic-ai", owner: "pydantic", description: "Agent framework powered by Pydantic. Type-safe, structured AI agent development.", stars: 12000, forks: 950, language: "Python", category: "ai-agents", topics: ["agents", "pydantic", "type-safe", "framework"], updated_at: "2026-07-10T09:00:00Z", readme: "## Pydantic AI\n\nAgent framework powered by Pydantic.\n\n### Why Pydantic AI\n\n- **Type-safe** — Full type hints and validation\n- **Structured Output** — Pydantic models as response schemas\n- **Dependency Injection** — Clean agent architecture\n- **OpenAI, Anthropic, Gemini** — Multi-provider\n\n### Quick Start\n\n```bash\npip install pydantic-ai\n```" },

  // ── Vibe Coding ──
  { id: 6, name: "awesome-vibe-coding", full_name: "filipecalegario/awesome-vibe-coding", owner: "filipecalegario", description: "A curated list of awesome Vibe Coding resources, tools, and best practices for AI-assisted development.", stars: 5800, forks: 420, language: "Markdown", category: "vibe-coding", topics: ["vibe-coding", "awesome-list", "ai-tools", "resources"], updated_at: "2026-07-08T10:00:00Z", readme: "## Awesome Vibe Coding\n\nA curated list of awesome Vibe Coding resources, tools, tutorials, and best practices for AI-assisted development.\n\n### Contents\n\n- Browser-based Tools\n- IDEs and Code Editors\n- Command Line Tools\n- Task Management\n- Documentation\n\n### Quick Start\n\nBrowse the categories to find tools that match your workflow." },
  { id: 7, name: "vibe-coding-prompt-template", full_name: "KhazP/vibe-coding-prompt-template", owner: "KhazP", description: "5-phase prompt template for AI-driven development. Research, PRD, Design, Config, Build.", stars: 2800, forks: 160, language: "Markdown", category: "vibe-coding", topics: ["vibe-coding", "prompts", "template", "workflow"], updated_at: "2026-06-20T12:00:00Z", readme: "## Vibe Coding Prompt Template\n\nA comprehensive 5-phase template for AI-driven development.\n\n### The 5 Phases\n\n1. **Deep Research** — Validate the idea\n2. **PRD Generation** — Define WHAT to build\n3. **Tech Design** — Define HOW to build\n4. **Agent Config** — Generate AI agent files\n5. **Build MVP** — Execute and iterate" },
  { id: 8, name: "bolt.new", full_name: "stackblitz/bolt.new", owner: "stackblitz", description: "Prompt, run, edit, and deploy full-stack web applications directly in the browser with AI.", stars: 15000, forks: 3200, language: "TypeScript", category: "vibe-coding", topics: ["ai", "web-app", "browser-ide", "stackblitz"], updated_at: "2026-07-09T16:00:00Z", readme: "## Bolt.new\n\nPrompt, run, edit, and deploy full-stack web apps in your browser.\n\n### Features\n\n- **AI-powered** — Describe what you want to build\n- **Full-stack** — Frontend + backend in one prompt\n- **Instant deploy** — Share with one click\n- **Edit & iterate** — Modify with natural language" },
  { id: 9, name: "lovable", full_name: "lovable/lovable", owner: "lovable", description: "AI-powered full-stack development platform. Turn ideas into applications instantly.", stars: 4200, forks: 580, language: "TypeScript", category: "vibe-coding", topics: ["ai", "fullstack", "no-code", "builder"], updated_at: "2026-07-07T12:00:00Z", readme: "## Lovable\n\nAI-powered full-stack development platform.\n\n### Features\n\n- **Instant apps** — Describe, get a working app\n- **Visual editor** — Refine with drag-and-drop\n- **Database** — Built-in PostgreSQL\n- **Authentication** — Built-in auth flows\n- **Deploy** — One-click deployment" },
  { id: 10, name: "windsurf", full_name: "windsurf-ai/windsurf", owner: "windsurf-ai", description: "Agentic IDE powered by AI. Next-generation coding assistant with deep code context.", stars: 8500, forks: 720, language: "TypeScript", category: "vibe-coding", topics: ["ide", "ai", "code-editor", "agentic"], updated_at: "2026-07-10T11:00:00Z", readme: "## Windsurf\n\nAgentic IDE powered by AI.\n\n### Key Features\n\n- **Cascade** — Multi-step AI agent that understands your codebase\n- **Flow** — Real-time AI suggestions as you type\n- **Context Awareness** — Full project understanding\n- **Multi-file Editing** — AI edits across files\n\n### Platforms\n\nmacOS, Windows, Linux" },

  // ── MCP & Protocols ──
  { id: 11, name: "vibe-check-mcp-server", full_name: "PV-Bhat/vibe-check-mcp-server", owner: "PV-Bhat", description: "MCP server implementing Chain-Pattern Interrupt (CPI) for AI agent oversight and safety.", stars: 1500, forks: 90, language: "TypeScript", category: "mcp", topics: ["mcp", "ai-safety", "monitoring", "agents"], updated_at: "2026-06-15T10:00:00Z", readme: "## Vibe Check MCP Server\n\nA plug-and-play mentor layer for AI agents implementing CPI.\n\n### Research-Backed\n\n+27% task success, -41% harmful actions, 153 eval runs\n\n### Quick Start\n\n```bash\nnpx -y @pv-bhat/vibe-check-mcp start --stdio\n```" },
  { id: 12, name: "modelcontextprotocol", full_name: "modelcontextprotocol/servers", owner: "modelcontextprotocol", description: "Official MCP server implementations by Anthropic. Reference servers for the Model Context Protocol.", stars: 22000, forks: 2100, language: "TypeScript", category: "mcp", topics: ["mcp", "anthropic", "protocol", "servers"], updated_at: "2026-07-11T08:00:00Z", readme: "## MCP Servers\n\nOfficial MCP server implementations by Anthropic.\n\n### Available Servers\n\n- **Filesystem** — Secure file operations\n- **GitHub** — Repository management\n- **PostgreSQL** — Database querying\n- **Sentry** — Error tracking\n- **Slack** — Messaging\n- **Puppeteer** — Browser automation\n\n### Quick Start\n\n```bash\nnpx @modelcontextprotocol/server-filesystem /path\n```" },
  { id: 13, name: "claude-code-mcp", full_name: "anthropics/claude-code-mcp", owner: "anthropics", description: "MCP servers for Claude Code. Extend Claude Code with custom tools and integrations.", stars: 4800, forks: 350, language: "TypeScript", category: "mcp", topics: ["mcp", "claude-code", "tools", "anthropic"], updated_at: "2026-07-10T14:00:00Z", readme: "## Claude Code MCP\n\nMCP servers for Claude Code.\n\n### Built-in Servers\n\n- **File System** — Read/write files\n- **Shell** — Execute commands\n- **Git** — Version control\n- **Search** — Code search\n\n### Custom Servers\n\nBuild your own with the MCP SDK." },
  { id: 14, name: "fastmcp", full_name: "jlowin/fastmcp", owner: "jlowin", description: "High-performance Python framework for building MCP servers with minimal boilerplate.", stars: 6200, forks: 320, language: "Python", category: "mcp", topics: ["mcp", "python", "framework", "server"], updated_at: "2026-07-09T09:00:00Z", readme: "## FastMCP\n\nHigh-performance Python framework for MCP servers.\n\n### Example\n\n```python\nfrom fastmcp import FastMCP\n\nmcp = FastMCP(\"My Server\")\n\n@mcp.tool()\ndef hello(name: str) -> str:\n    return f\"Hello {name}!\"\n\nmcp.run()\n```" },
  { id: 15, name: "mcp-github", full_name: "PKief/mcp-github", owner: "PKief", description: "MCP server for GitHub API integration. Manage repos, issues, PRs, and code reviews.", stars: 3900, forks: 280, language: "TypeScript", category: "mcp", topics: ["mcp", "github", "api", "integration"], updated_at: "2026-07-08T15:00:00Z", readme: "## MCP GitHub\n\nMCP server for GitHub API.\n\n### Tools\n\n- **create_repository** — Create new repos\n- **create_issue** — File issues\n- **create_pull_request** — Open PRs\n- **search_code** — Search across repos\n- **get_file_contents** — Read files" },

  // ── LLM APIs & SDKs ──
  { id: 16, name: "openai-python", full_name: "openai/openai-python", owner: "openai", description: "Official Python library for the OpenAI API. Chat completions, embeddings, assistants, and more.", stars: 26000, forks: 5200, language: "Python", category: "llm-tools", topics: ["openai", "python", "api", "sdk"], updated_at: "2026-07-11T06:00:00Z", readme: "## OpenAI Python Library\n\nOfficial Python library for the OpenAI API.\n\n### Installation\n\n```bash\npip install openai\n```\n\n### Quick Start\n\n```python\nfrom openai import OpenAI\nclient = OpenAI()\nresponse = client.chat.completions.create(\n    model=\"gpt-5\",\n    messages=[{\"role\": \"user\", \"content\": \"Hello\"}]\n)\n```" },
  { id: 17, name: "anthropic-sdk-python", full_name: "anthropics/anthropic-sdk-python", owner: "anthropics", description: "Official Python SDK for Anthropic's Claude API. Messages, tool use, and streaming support.", stars: 5200, forks: 1100, language: "Python", category: "llm-tools", topics: ["anthropic", "claude", "python", "sdk"], updated_at: "2026-07-10T18:00:00Z", readme: "## Anthropic SDK Python\n\nOfficial Python SDK for the Anthropic API.\n\n### Installation\n\n```bash\npip install anthropic\n```\n\n### Quick Start\n\n```python\nfrom anthropic import Anthropic\nclient = Anthropic()\nresponse = client.messages.create(\n    model=\"claude-sonnet-5\",\n    max_tokens=1024,\n    messages=[{\"role\": \"user\", \"content\": \"Hello\"}]\n)\n```" },
  { id: 18, name: "google-gemini", full_name: "google-gemini/generative-ai-python", owner: "google-gemini", description: "Official Python SDK for Google Gemini API. Multimodal, streaming, and safety features.", stars: 8500, forks: 1800, language: "Python", category: "llm-tools", topics: ["google", "gemini", "python", "sdk", "ai"], updated_at: "2026-07-09T20:00:00Z", readme: "## Google Gemini SDK\n\nOfficial Python SDK for Google's Gemini models.\n\n### Installation\n\n```bash\npip install google-generativeai\n```\n\n### Quick Start\n\n```python\nimport google.generativeai as genai\ngenai.configure(api_key=\"...\")\nmodel = genai.GenerativeModel(\"gemini-3.1-pro\")\nresponse = model.generate_content(\"Hello\")\n```" },
  { id: 19, name: "llamaindex", full_name: "run-llama/llama_index", owner: "run-llama", description: "Data framework for LLM applications. Ingestion, indexing, retrieval, and querying over your data.", stars: 39000, forks: 5200, language: "Python", category: "llm-tools", topics: ["llm", "rag", "index", "data-framework"], updated_at: "2026-07-11T07:00:00Z", readme: "## LlamaIndex\n\nData framework for LLM applications.\n\n### Key Abstractions\n\n- **Documents** — Input data\n- **Nodes** — Chunks of documents\n- **Indices** — Structured for retrieval\n- **Retrievers** — Fetch relevant nodes\n- **Query Engines** — End-to-end Q&A\n\n### Quick Start\n\n```bash\npip install llama-index\n```" },
  { id: 20, name: "vllm", full_name: "vllm-project/vllm", owner: "vllm-project", description: "High-throughput, memory-efficient LLM serving engine with PagedAttention and continuous batching.", stars: 48000, forks: 7200, language: "Python", category: "llm-tools", topics: ["llm", "inference", "serving", "optimization"], updated_at: "2026-07-10T22:00:00Z", readme: "## vLLM\n\nHigh-throughput LLM serving engine.\n\n### Features\n\n- **PagedAttention** — Efficient memory management\n- **Continuous Batching** — Maximize throughput\n- **Tensor Parallel** — Multi-GPU inference\n- **OpenAI-compatible API** — Drop-in replacement\n\n### Quick Start\n\n```bash\npip install vllm\npython -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-4-70b\n```" },

  // ── Fine-tuning & Training ──
  { id: 21, name: "unsloth", full_name: "unslothai/unsloth", owner: "unslothai", description: "2x faster LLM fine-tuning with reduced memory. Supports Llama, Mistral, Gemma, and more.", stars: 28000, forks: 2600, language: "Python", category: "fine-tuning", topics: ["fine-tuning", "llm", "optimization", "training"], updated_at: "2026-07-10T16:00:00Z", readme: "## Unsloth\n\n2x faster LLM fine-tuning with less memory.\n\n### Supported Models\n\nLlama 4, Mistral, Gemma 3, Qwen 3.7, DeepSeek V4, Phi-4\n\n### Quick Start\n\n```python\nfrom unsloth import FastLanguageModel\nmodel, tokenizer = FastLanguageModel.from_pretrained(\n    \"unsloth/Llama-4-8b\",\n    max_seq_length=4096\n)\n```\n\n### Memory Savings\n\n- 2x less memory vs standard LoRA\n- 4x less memory vs full fine-tune" },
  { id: 22, name: "axolotl", full_name: "OpenAccess-AI-Collective/axolotl", owner: "OpenAccess-AI-Collective", description: "Streamlined fine-tuning framework for LLMs. YAML-based configuration, multi-GPU support.", stars: 12000, forks: 1900, language: "Python", category: "fine-tuning", topics: ["fine-tuning", "llm", "training", "framework"], updated_at: "2026-07-09T12:00:00Z", readme: "## Axolotl\n\nStreamlined LLM fine-tuning framework.\n\n### Features\n\n- **YAML Config** — Declarative training setup\n- **Multi-GPU** — FSDP, DeepSpeed, DDP\n- **LoRA/QLoRA** — Parameter-efficient tuning\n- **Wandb Integration** — Training metrics\n\n### Quick Start\n\n```bash\npip install axolotl\naccelerate launch -m axolotl.cli.train config.yml\n```" },
  { id: 23, name: "llama.cpp", full_name: "ggml-ai/llama.cpp", owner: "ggml-ai", description: "LLM inference in C/C++. Run quantized LLMs on CPU, GPU, and edge devices. GGUF format.", stars: 78000, forks: 11000, language: "C++", category: "fine-tuning", topics: ["llm", "inference", "cpp", "quantization", "gguf"], updated_at: "2026-07-11T05:00:00Z", readme: "## llama.cpp\n\nLLM inference in C/C++.\n\n### Key Features\n\n- **GGUF** — Quantized model format\n- **CPU/GPU** — Runs everywhere\n- **Server Mode** — HTTP API\n- **Embeddings** — Generate embeddings\n\n### Quick Start\n\n```bash\ncmake -B build\ncmake --build build --config Release\n./build/bin/llama-server -m model.gguf\n```" },
  { id: 24, name: "torchtune", full_name: "pytorch/torchtune", owner: "pytorch", description: "Native PyTorch LLM fine-tuning. LoRA, QLoRA, full fine-tune with FSDP and distributed training.", stars: 4500, forks: 480, language: "Python", category: "fine-tuning", topics: ["pytorch", "fine-tuning", "llm", "distributed"], updated_at: "2026-07-08T08:00:00Z", readme: "## Torchtune\n\nNative PyTorch LLM fine-tuning.\n\n### Features\n\n- **LoRA/QLoRA** — PEFT methods\n- **Full Fine-tune** — Distributed with FSDP\n- **Recipe System** — Configurable recipes\n- **Memory Efficient** — Activation offloading\n\n### Quick Start\n\n```bash\npip install torchtune\ntune run lora_finetune --config llama4_8b_lora\n```" },
  { id: 25, name: "open-instruct", full_name: "allenai/open-instruct", owner: "allenai", description: "Open-source instruction tuning for LLMs. Training data, recipes, and evaluation tools.", stars: 6200, forks: 780, language: "Python", category: "fine-tuning", topics: ["instruction-tuning", "llm", "training", "allenai"], updated_at: "2026-07-07T14:00:00Z", readme: "## Open Instruct\n\nOpen-source instruction tuning.\n\n### Components\n\n- **Training Data** — Curated instruction datasets\n- **Training Recipes** — Reproducible fine-tuning\n- **Evaluation** — Standardized benchmarks\n- **Models** — Pre-trained instruct models\n\n### Quick Start\n\n```bash\npip install -e .\nbash scripts/train.sh\n```" },

  // ── Embeddings & Vector DBs ──
  { id: 26, name: "chroma", full_name: "chroma-core/chroma", owner: "chroma-core", description: "AI-native open-source embedding database. Fast vector search with built-in embedding models.", stars: 18000, forks: 1500, language: "Python", category: "data-tools", topics: ["vector-database", "embeddings", "rag", "semantic-search"], updated_at: "2026-07-10T13:00:00Z", readme: "## Chroma\n\nAI-native open-source embedding database.\n\n### Features\n\n- **Built-in Embeddings** — No separate model needed\n- **Fast Search** — ANN with HNSW\n- **Multi-modal** — Text, images, audio\n- **Metadata Filtering** — Structured search\n\n### Quick Start\n\n```python\nimport chromadb\nclient = chromadb.Client()\ncollection = client.create_collection(\"docs\")\ncollection.add(documents=[\"Hello\"], ids=[\"1\"])\n```" },
  { id: 27, name: "weaviate", full_name: "weaviate/weaviate", owner: "weaviate", description: "Open-source vector database with built-in vectorization, hybrid search, and generative AI features.", stars: 12500, forks: 1100, language: "Go", category: "data-tools", topics: ["vector-database", "semantic-search", "ai", "graphql"], updated_at: "2026-07-10T17:00:00Z", readme: "## Weaviate\n\nOpen-source vector database.\n\n### Key Features\n\n- **Hybrid Search** — Vector + keyword\n- **Generative Search** — RAG built-in\n- **Multi-tenancy** — Isolated data\n- **GraphQL API** — Flexible queries\n\n### Quick Start\n\n```bash\ndocker compose up -d\n```" },
  { id: 28, name: "qdrant", full_name: "qdrant/qdrant", owner: "qdrant", description: "High-performance vector similarity search engine. Rust-based, production-ready, with filtering.", stars: 23000, forks: 1500, language: "Rust", category: "data-tools", topics: ["vector-search", "rust", "nearest-neighbor", "embeddings"], updated_at: "2026-07-11T04:00:00Z", readme: "## Qdrant\n\nHigh-performance vector search engine.\n\n### Features\n\n- **Rust** — Blazing fast, memory safe\n- **Payload Filtering** — Complex filters\n- **Quantization** — Scalar, product\n- **Distributed** — Horizontal scaling\n\n### Quick Start\n\n```bash\ndocker run -p 6333:6333 qdrant/qdrant\n```" },

  // ── Prompt Engineering ──
  { id: 29, name: "context-engineering-intro", full_name: "coleam00/context-engineering-intro", owner: "coleam00", description: "Introduction to Context Engineering for AI agents. PRP methodology and best practices.", stars: 3200, forks: 180, language: "Markdown", category: "workflow", topics: ["context-engineering", "prp", "ai-agents", "workflow"], updated_at: "2026-06-25T08:00:00Z", readme: "## Context Engineering Intro\n\nA comprehensive introduction to Context Engineering.\n\n### The PRP Framework\n\n**P**rompt **R**esource **P**ackage — structured document for AI.\n\n1. **INITIAL.md** — Define what to build\n2. **/generate-prp** — Research + create PRP\n3. **/execute-prp** — Read PRP and implement\n\n### WISC Framework\n\n- **W**rite — Externalize agent memory\n- **I**solate — Sub-agents for focused tasks\n- **S**elect — Load only needed context\n- **C**ompress — Compact when sessions get long" },
  { id: 30, name: "rulebook-ai", full_name: "botingw/rulebook-ai", owner: "botingw", description: "Rule management system for AI coding assistants. Pack-based architecture with Memory Bank.", stars: 1200, forks: 75, language: "Python", category: "workflow", topics: ["ai-rules", "workflow", "claude-code", "cursor"], updated_at: "2026-06-10T09:00:00Z", readme: "## Rulebook AI\n\nRule management system for AI coding assistants.\n\n### Pack System\n\n- **manifest.yaml** — Name, version, summary\n- **rules/** — Numbered rule directories\n- **memory_starters/** — Template docs\n- **tool_starters/** — Utility scripts\n\n### Supported Assistants\n\nCursor, Windsurf, Cline, RooCode, Claude Code, Copilot, Gemini CLI" },
  { id: 31, name: "fabric", full_name: "danielmiessler/fabric", owner: "danielmiessler", description: "Open-source framework for augmenting human capability using AI. Pattern-based prompt library.", stars: 32000, forks: 3300, language: "Go", category: "workflow", topics: ["prompts", "ai", "patterns", "framework"], updated_at: "2026-07-10T20:00:00Z", readme: "## Fabric\n\nOpen-source framework for augmenting human capability using AI.\n\n### Key Concepts\n\n- **Patterns** — Reusable AI prompts and workflows\n- **Mill** — Pattern execution engine\n- **APIs** — Connect to any LLM\n\n### Quick Start\n\n```bash\npip install fabric-ai\nfabric --pattern summarize --input article.txt\n```\n\n### Example Patterns\n\n- `summarize` — Smart text summarization\n- `extract_wisdom` — Key insights from content\n- `write_essay` — Structured essay generation" },
  { id: 32, name: "promptfoo", full_name: "promptfoo/promptfoo", owner: "promptfoo", description: "Prompt testing and evaluation framework. Red teaming, LLM eval, and prompt engineering toolkit.", stars: 12000, forks: 1200, language: "TypeScript", category: "workflow", topics: ["prompts", "evaluation", "testing", "llmops"], updated_at: "2026-07-11T03:00:00Z", readme: "## Promptfoo\n\nPrompt testing and evaluation framework.\n\n### Features\n\n- **Eval** — Compare model outputs side-by-side\n- **Red Teaming** — Automated adversarial testing\n- **CI/CD** — Integrate with your pipeline\n- **Provider Agnostic** — OpenAI, Anthropic, local\n\n### Quick Start\n\n```bash\nnpx promptfoo eval\n```" },

  // ── UI/UX Tools ──
  { id: 33, name: "ui-ux-pro-max-skill", full_name: "nextlevelbuilder/ui-ux-pro-max-skill", owner: "nextlevelbuilder", description: "Production-level UI/UX skill for Claude Code. Design system, tokens, and component specs.", stars: 4100, forks: 250, language: "TypeScript", category: "ui-ux", topics: ["ui-ux", "claude-code", "design-system", "css"], updated_at: "2026-07-01T14:00:00Z", readme: "## UI/UX Pro Max — Design Intelligence\n\nA production-level UI/UX skill for Claude Code.\n\n### Features\n\n- **Design Dials**: variance, motion, density\n- **22 Stack Guidelines**: React, Vue, Angular, SwiftUI\n- **161 Color Palettes**: Industry-specific, WCAG\n- **57 Font Pairings**: Curated typography" },
  { id: 34, name: "shadcn-ui", full_name: "shadcn-ui/ui", owner: "shadcn-ui", description: "Beautifully designed components built with Radix UI and Tailwind CSS. Copy-paste components.", stars: 82000, forks: 5200, language: "TypeScript", category: "ui-ux", topics: ["react", "components", "tailwindcss", "design-system"], updated_at: "2026-07-11T02:00:00Z", readme: "## shadcn/ui\n\nBeautifully designed React components.\n\n### Features\n\n- **Copy-paste** — Own your components\n- **Customizable** — Tailwind CSS theming\n- **Accessible** — Radix UI primitives\n- **Dark mode** — Built-in support\n\n### Quick Start\n\n```bash\nnpx shadcn@latest init\n```" },
  { id: 35, name: "design-resources-for-developers", full_name: "bradtraversy/design-resources-for-developers", owner: "bradtraversy", description: "Curated list of design and UI resources from stock photos to web design tools.", stars: 62000, forks: 5600, language: "Markdown", category: "ui-ux", topics: ["design", "resources", "ui", "ux"], updated_at: "2026-05-20T10:00:00Z", readme: "## Design Resources for Developers\n\nCurated list of design and UI resources.\n\n### Categories\n\n- UI/UX Tools\n- Color Tools\n- Typography\n- Stock Photos\n- Icons\n- Illustrations" },
  { id: 36, name: "radix-ui", full_name: "radix-ui/primitives", owner: "radix-ui", description: "Unstyled, accessible React UI component library. The foundation for design systems.", stars: 18000, forks: 1200, language: "TypeScript", category: "ui-ux", topics: ["react", "ui", "accessible", "primitives"], updated_at: "2026-07-09T15:00:00Z", readme: "## Radix UI\n\nUnstyled, accessible React components.\n\n### Primitives\n\n- Dialog, Popover, Tooltip, Dropdown Menu\n- Select, Tabs, Accordion, Toast\n- Slider, Switch, Checkbox, Radio\n\n### Design System Ready\n\nNo built-in styles — bring your own design system." },

  // ── Learning & Resources ──
  { id: 37, name: "developer-roadmap", full_name: "kamranahmedse/developer-roadmap", owner: "kamranahmedse", description: "Interactive roadmaps, guides and educational content to help developers grow and navigate tech.", stars: 310000, forks: 42000, language: "TypeScript", category: "learning", topics: ["roadmap", "learning", "developer", "career"], updated_at: "2026-06-30T16:00:00Z", readme: "## Developer Roadmap\n\nCommunity-driven roadmaps, articles and resources for developers.\n\n### Roadmaps\n\n- Frontend, Backend, DevOps, Full Stack\n- AI/ML, Android, PostgreSQL, Rust\n- Go, Python, Java, Kubernetes" },
  { id: 38, name: "system-design-101", full_name: "ByteByteGoHq/system-design-101", owner: "ByteByteGoHq", description: "Explain complex systems using visual aids and simple terms. System design fundamentals.", stars: 75000, forks: 7800, language: "Markdown", category: "learning", topics: ["system-design", "architecture", "visualization"], updated_at: "2026-06-28T11:00:00Z", readme: "## System Design 101\n\nExplain complex systems using visual aids.\n\n### Topics\n\nDNS, CDN, Load Balancers, API Gateway, Databases, Caching, Message Queues, Microservices, Distributed Systems" },
  { id: 39, name: "ml-for-beginners", full_name: "microsoft/ml-for-beginners", owner: "microsoft", description: "12-week, 26-lesson curriculum on machine learning fundamentals by Microsoft Cloud Advocates.", stars: 72000, forks: 15000, language: "Jupyter Notebook", category: "learning", topics: ["machine-learning", "education", "curriculum", "microsoft"], updated_at: "2026-07-05T12:00:00Z", readme: "## ML for Beginners\n\n12-week, 26-lesson ML curriculum.\n\n### Topics\n\n- Regression, Classification, Clustering\n- Natural Language Processing\n- Time Series Forecasting\n- Reinforcement Learning\n- Neural Networks" },
  { id: 40, name: "generative-ai-for-beginners", full_name: "microsoft/generative-ai-for-beginners", owner: "microsoft", description: "18-lesson curriculum on Generative AI covering RAG, agents, fine-tuning, and responsible AI.", stars: 34000, forks: 18000, language: "Jupyter Notebook", category: "learning", topics: ["generative-ai", "llm", "education", "curriculum"], updated_at: "2026-07-06T14:00:00Z", readme: "## Generative AI for Beginners\n\n18-lesson Generative AI curriculum.\n\n### Topics\n\n- LLM Fundamentals\n- Prompt Engineering\n- RAG Architectures\n- AI Agents\n- Fine-tuning\n- Responsible AI" },
  { id: 41, name: "openai-cookbook", full_name: "openai/openai-cookbook", owner: "openai", description: "Examples and guides for using the OpenAI API. RAG, function calling, embeddings, and more.", stars: 63000, forks: 10500, language: "Python", category: "learning", topics: ["openai", "examples", "cookbook", "guides"], updated_at: "2026-07-10T21:00:00Z", readme: "## OpenAI Cookbook\n\nExamples and guides for the OpenAI API.\n\n### Contents\n\n- RAG patterns and implementations\n- Function calling examples\n- Embeddings and vector search\n- Text-to-speech and speech-to-text\n- Image generation and analysis" },
  { id: 42, name: "anthropic-cookbook", full_name: "anthropics/anthropic-cookbook", owner: "anthropics", description: "Cookbook for building with Claude. Tool use, agents, prompt engineering, and production patterns.", stars: 15000, forks: 1800, language: "Python", category: "learning", topics: ["anthropic", "claude", "examples", "cookbook"], updated_at: "2026-07-10T19:00:00Z", readme: "## Anthropic Cookbook\n\nCookbook for building with Claude.\n\n### Chapters\n\n- Tool Use and Function Calling\n- Multi-agent Orchestration\n- Prompt Engineering Best Practices\n- RAG with Claude\n- Vision and Multimodal\n- Production Deployment" },
  { id: 43, name: "awesome-llm-apps", full_name: "Shubhamsaboo/awesome-llm-apps", owner: "Shubhamsaboo", description: "Collection of LLM-powered applications. RAG, agents, chatbots, and AI tools with source code.", stars: 8500, forks: 1100, language: "Python", category: "learning", topics: ["llm", "apps", "rag", "agents", "examples"], updated_at: "2026-07-09T18:00:00Z", readme: "## Awesome LLM Apps\n\nCollection of LLM-powered applications with complete source code.\n\n### App Categories\n\n- Chatbots & Assistants\n- RAG Systems\n- AI Agents\n- Content Generation\n- Data Analysis" },

  // ── CLI & Developer Tools ──
  { id: 44, name: "claude-code", full_name: "anthropics/claude-code", owner: "anthropics", description: "AI-powered terminal-based development agent by Anthropic. Code editing, git, and more.", stars: 18000, forks: 950, language: "TypeScript", category: "tools", topics: ["ai", "cli", "developer-tools", "anthropic"], updated_at: "2026-07-10T20:00:00Z", readme: "## Claude Code\n\nAI-powered terminal-based development agent.\n\n### Features\n\n- Code generation and editing\n- Terminal commands\n- Git integration\n- Multi-file editing\n- Agent mode\n\n### Quick Start\n\n```bash\nnpm install -g @anthropic-ai/claude-code\nclaude\n```" },
  { id: 45, name: "firecrawl", full_name: "firecrawl/firecrawl", owner: "firecrawl", description: "Turn websites into LLM-ready data. Crawl and convert any website into clean markdown.", stars: 28000, forks: 2100, language: "TypeScript", category: "tools", topics: ["web-scraping", "llm", "crawler", "data-extraction"], updated_at: "2026-07-02T08:00:00Z", readme: "## Firecrawl\n\nTurn websites into LLM-ready data.\n\n### Features\n\n- URL to LLM-ready markdown\n- Full website crawling\n- Scheduled crawling\n- Custom extraction rules\n\n### Quick Start\n\n```python\nfrom firecrawl import FirecrawlApp\napp = FirecrawlApp(api_key=\"fc-...\")\nmarkdown = app.scrape_url(\"https://example.com\")\n```" },
  { id: 46, name: "cline", full_name: "cline/cline", owner: "cline", description: "Autonomous coding agent for VS Code. AI-powered code generation, refactoring, and debugging.", stars: 22000, forks: 2100, language: "TypeScript", category: "tools", topics: ["vscode", "agent", "ai", "extension"], updated_at: "2026-07-10T15:00:00Z", readme: "## Cline\n\nAutonomous coding agent for VS Code.\n\n### Features\n\n- Autonomous code generation\n- Multi-file editing\n- Terminal integration\n- Bug detection and fixing\n- Refactoring\n\n### Install\n\nSearch \"Cline\" in VS Code marketplace." },
  { id: 47, name: "aider", full_name: "paul-gauthier/aider", owner: "paul-gauthier", description: "AI pair programming in terminal. Code editing with Claude, GPT, and local models. Git-aware.", stars: 32000, forks: 2900, language: "Python", category: "tools", topics: ["ai", "coding", "cli", "pair-programming"], updated_at: "2026-07-11T01:00:00Z", readme: "## Aider\n\nAI pair programming in the terminal.\n\n### Features\n\n- Multi-model support (Claude, GPT, local)\n- Git-aware edits\n- Automatic commit messages\n- Architecture analysis\n\n### Quick Start\n\n```bash\npip install aider-chat\nexport ANTHROPIC_API_KEY=sk-...\naider\n```" },
  { id: 48, name: "continue", full_name: "continuedev/continue", owner: "continuedev", description: "Open-source AI code assistant for VS Code and JetBrains. Custom models, context, and rules.", stars: 25000, forks: 2300, language: "TypeScript", category: "tools", topics: ["vscode", "jetbrains", "ai", "assistant"], updated_at: "2026-07-10T23:00:00Z", readme: "## Continue\n\nOpen-source AI code assistant.\n\n### Features\n\n- Custom models (OpenAI, Anthropic, local)\n- Context providers (files, terminal, search)\n- Custom slash commands\n- Rules and instructions\n\n### Install\n\nVS Code marketplace or JetBrains plugin." },
  { id: 49, name: "tabby", full_name: "TabbyML/tabby", owner: "TabbyML", description: "Self-hosted AI coding assistant. Code completion, chat, and search with local LLMs.", stars: 26000, forks: 1100, language: "Rust", category: "tools", topics: ["code-completion", "self-hosted", "llm", "rust"], updated_at: "2026-07-10T10:00:00Z", readme: "## Tabby\n\nSelf-hosted AI coding assistant.\n\n### Features\n\n- Code completion inline\n- Chat interface\n- Code search\n- Local LLM support\n- Team deployment\n\n### Quick Start\n\n```bash\ndocker run -p 8080:8080 tabbyml/tabby\n```" },
  { id: 50, name: "open-interpreter", full_name: "openinterpreter/open-interpreter", owner: "openinterpreter", description: "Natural language interface for computers. Run code, control apps, browse web — all via chat.", stars: 58000, forks: 5100, language: "Python", category: "tools", topics: ["assistant", "automation", "cli", "code-execution"], updated_at: "2026-07-09T22:00:00Z", readme: "## Open Interpreter\n\nNatural language interface for computers.\n\n### Capabilities\n\n- Run Python, JavaScript, Shell\n- Control browser and apps\n- Read/write files\n- Web browsing and search\n- Data analysis\n\n### Quick Start\n\n```bash\npip install open-interpreter\ninterpreter\n```" },
  { id: 51, name: "screenpipe", full_name: "mediar-ai/screenpipe", owner: "mediar-ai", description: "Continuous screen and audio capture for AI. Build context-aware agents with screen context.", stars: 14000, forks: 820, language: "Rust", category: "tools", topics: ["screen-capture", "context", "agents", "automation"], updated_at: "2026-07-10T06:00:00Z", readme: "## Screenpipe\n\nContinuous screen and audio capture for AI.\n\n### Features\n\n- Real-time screen capture\n- Audio recording with transcription\n- OCR and text extraction\n- Embedding generation\n- Context-aware agent triggers\n\n### Quick Start\n\n```bash\npip install screenpipe\nscreenpipe --record\n```" },
  { id: 52, name: "uv", full_name: "astral-sh/uv", owner: "astral-sh", description: "Extremely fast Python package manager. Drop-in replacement for pip, pip-tools, and virtualenv.", stars: 42000, forks: 1200, language: "Rust", category: "tools", topics: ["python", "package-manager", "rust", "tooling"], updated_at: "2026-07-11T00:00:00Z", readme: "## uv\n\nExtremely fast Python package manager.\n\n### Features\n\n- 10-100x faster than pip\n- Pip-compatible interface\n- Virtual environments built-in\n- Dependency resolution\n- Tool management\n\n### Quick Start\n\n```bash\npip install uv\nuv venv\nuv pip install -r requirements.txt\n```" },

  // ── RAG & Search ──
  { id: 53, name: "graphrag", full_name: "microsoft/graphrag", owner: "microsoft", description: "Graph-based RAG system. Extracts structured knowledge from documents for LLM question answering.", stars: 22000, forks: 2200, language: "Python", category: "data-tools", topics: ["rag", "knowledge-graph", "microsoft", "search"], updated_at: "2026-07-10T12:00:00Z", readme: "## GraphRAG\n\nGraph-based RAG system.\n\n### How It Works\n\n1. **Extract** entities and relationships from documents\n2. **Build** a knowledge graph\n3. **Query** using graph traversal + LLM\n4. **Answer** with structured context\n\n### Quick Start\n\n```bash\npip install graphrag\npython -m graphrag.index --input ./documents\n```" },
  { id: 54, name: "milvus", full_name: "milvus-io/milvus", owner: "milvus-io", description: "Cloud-native vector database for AI applications. Trillion-scale similarity search with GPU support.", stars: 33000, forks: 3400, language: "Go", category: "data-tools", topics: ["vector-database", "search", "gpu", "distributed"], updated_at: "2026-07-10T16:00:00Z", readme: "## Milvus\n\nCloud-native vector database.\n\n### Features\n\n- Trillion-scale vector search\n- GPU acceleration\n- Hybrid search (vector + scalar)\n- Multi-tenancy\n- Streaming and batch ingestion\n\n### Quick Start\n\n```bash\ndocker compose -f milvus.yaml up -d\n```" },
  { id: 55, name: "txtai", full_name: "neuml/txtai", owner: "neuml", description: "AI-powered semantic search and workflows. Embeddings database, RAG pipelines, and AI agent framework.", stars: 9500, forks: 820, language: "Python", category: "data-tools", topics: ["semantic-search", "rag", "embeddings", "workflow"], updated_at: "2026-07-09T11:00:00Z", readme: "## txtai\n\nAI-powered semantic search.\n\n### Components\n\n- **Embeddings** — Vector search database\n- **Pipelines** — RAG and data processing\n- **Workflows** — Multi-step automation\n- **Agents** — Autonomous task execution\n\n### Quick Start\n\n```bash\npip install txtai\n```" },

  // ── Multi-modal & Image ──
  { id: 56, name: "diffusers", full_name: "huggingface/diffusers", owner: "huggingface", description: "State-of-the-art diffusion models for image and video generation. Training and inference.", stars: 28000, forks: 5000, language: "Python", category: "ai-agents", topics: ["diffusion", "image-generation", "huggingface", "deep-learning"], updated_at: "2026-07-10T11:00:00Z", readme: "## Diffusers\n\nState-of-the-art diffusion models.\n\n### Features\n\n- Text-to-Image (Stable Diffusion, FLUX)\n- Image-to-Image\n- Video generation\n- Fine-tuning and LoRA\n- Custom pipelines\n\n### Quick Start\n\n```bash\npip install diffusers transformers accelerate\n```" },
  { id: 57, name: "whisper", full_name: "openai/whisper", owner: "openai", description: "State-of-the-art speech recognition and transcription. Multilingual, supports 99 languages.", stars: 78000, forks: 9000, language: "Python", category: "ai-agents", topics: ["speech-recognition", "transcription", "openai", "multilingual"], updated_at: "2026-07-10T18:00:00Z", readme: "## Whisper\n\nState-of-the-art speech recognition.\n\n### Features\n\n- 99 languages supported\n- Multiple model sizes (tiny to large)\n- Translation to English\n- Punctuation and formatting\n\n### Quick Start\n\n```bash\npip install openai-whisper\nwhisper audio.mp3\n```" },
  { id: 58, name: "tesseract", full_name: "tesseract-ocr/tesseract", owner: "tesseract-ocr", description: "Open-source OCR engine. Text recognition from images with 100+ language support.", stars: 65000, forks: 9700, language: "C++", category: "tools", topics: ["ocr", "text-recognition", "computer-vision", "cplusplus"], updated_at: "2026-07-08T09:00:00Z", readme: "## Tesseract OCR\n\nOpen-source OCR engine.\n\n### Features\n\n- 100+ language support\n- Page layout analysis\n- Multi-column text detection\n- Custom training\n\n### Quick Start\n\n```bash\ntesseract image.png output\n```" },

  // ── Model Serving & Deployment ──
  { id: 59, name: "ollama", full_name: "ollama/ollama", owner: "ollama", description: "Get up and running with local LLMs. Run Llama, Mistral, Gemma, and more on your machine.", stars: 130000, forks: 11000, language: "Go", category: "llm-tools", topics: ["llm", "local", "go", "inference"], updated_at: "2026-07-11T06:00:00Z", readme: "## Ollama\n\nRun local LLMs with ease.\n\n### Supported Models\n\nLlama 4, Mistral, Gemma 3, Qwen 3.7, DeepSeek V4, Phi-4, Command R+\n\n### Quick Start\n\n```bash\ncurl -fsSL https://ollama.com/install.sh | sh\nollama run llama4\n```" },
  { id: 60, name: "langflow", full_name: "langflow-ai/langflow", owner: "langflow-ai", description: "Visual framework for building RAG and multi-agent applications. Drag-and-drop AI workflows.", stars: 45000, forks: 5100, language: "Python", category: "ai-agents", topics: ["rag", "agents", "visual", "low-code"], updated_at: "2026-07-10T17:00:00Z", readme: "## Langflow\n\nVisual framework for AI applications.\n\n### Features\n\n- Drag-and-drop interface\n- RAG pipeline builder\n- Multi-agent orchestration\n- API export\n- Custom components\n\n### Quick Start\n\n```bash\npip install langflow\nlangflow run\n```" },
  { id: 61, name: "open-webui", full_name: "open-webui/open-webui", owner: "open-webui", description: "ChatGPT-like web UI for local LLMs. Docker-based, multi-user, with RAG and tools support.", stars: 75000, forks: 8500, language: "TypeScript", category: "llm-tools", topics: ["webui", "llm", "docker", "chat"], updated_at: "2026-07-11T07:00:00Z", readme: "## Open WebUI\n\nChatGPT-like interface for local LLMs.\n\n### Features\n\n- Multi-user support\n- RAG pipelines\n- Tool integration\n- Model switching\n- Docker deployment\n\n### Quick Start\n\n```bash\ndocker run -d -p 3000:8080 ghcr.io/open-webui/open-webui:main\n```" },
  { id: 62, name: "khoj", full_name: "khoj-ai/khoj", owner: "khoj-ai", description: "AI second brain. Search, chat, and automate your personal knowledge base with local LLMs.", stars: 25000, forks: 1300, language: "Python", category: "tools", topics: ["knowledge-base", "search", "ai", "second-brain"], updated_at: "2026-07-10T14:00:00Z", readme: "## Khoj\n\nAI second brain.\n\n### Features\n\n- Semantic search across notes\n- AI chat with your data\n- Automated tagging\n- Cross-platform (Desktop, Mobile, API)\n- Local or cloud LLM\n\n### Quick Start\n\n```bash\npip install khoj\nkhoj start\n```" },
  { id: 63, name: "n8n", full_name: "n8n-io/n8n", owner: "n8n-io", description: "Workflow automation with AI capabilities. Fair-code, self-hostable with 400+ integrations.", stars: 65000, forks: 8700, language: "TypeScript", category: "workflow", topics: ["automation", "workflow", "low-code", "ai"], updated_at: "2026-07-10T15:00:00Z", readme: "## n8n\n\nWorkflow automation with AI.\n\n### Features\n\n- Visual workflow builder\n- 400+ integrations\n- AI nodes (LLM, RAG, Embeddings)\n- Self-hostable\n- Webhooks and triggers\n\n### Quick Start\n\n```bash\ndocker run -it --rm --name n8n -p 5678:5678 n8nio/n8n\n```" },
  { id: 64, name: "dify", full_name: "langgenius/dify", owner: "langgenius", description: "Open-source LLM application development platform. RAG engine, agent, workflow, and model hub.", stars: 48000, forks: 7100, language: "TypeScript", category: "llm-tools", topics: ["llm", "platform", "rag", "agents", "low-code"], updated_at: "2026-07-11T04:00:00Z", readme: "## Dify\n\nOpen-source LLM app platform.\n\n### Features\n\n- RAG pipeline engine\n- Agent orchestration\n- Workflow automation\n- Model hub (OpenAI, Anthropic, local)\n- API and SDK\n\n### Quick Start\n\n```bash\ndocker compose up -d\n```" },
  { id: 65, name: "composio", full_name: "composio/composio", owner: "composio", description: "Tool integration platform for AI agents. 200+ tools and APIs for agentic workflows.", stars: 12000, forks: 1400, language: "Python", category: "ai-agents", topics: ["agents", "tools", "integrations", "api"], updated_at: "2026-07-09T20:00:00Z", readme: "## Composio\n\nTool integration platform for AI agents.\n\n### Features\n\n- 200+ tool integrations\n- OAuth handling\n- Rate limiting\n- Usage tracking\n- Auto-generated function schemas\n\n### Quick Start\n\n```bash\npip install composio\ncomposio add github\n```" },
  { id: 66, name: "copilotkit", full_name: "CopilotKit/CopilotKit", owner: "CopilotKit", description: "Build deeply integrated AI copilots into your React apps. UI components, agents, and tools.", stars: 15000, forks: 2000, language: "TypeScript", category: "ui-ux", topics: ["react", "copilot", "ai", "ui-components"], updated_at: "2026-07-08T16:00:00Z", readme: "## CopilotKit\n\nBuild AI copilots into React apps.\n\n### Features\n\n- Inline AI chat component\n- Autocomplete suggestions\n- Agent integration\n- Tool execution\n- Streaming responses\n\n### Quick Start\n\n```bash\nnpm install @copilotkit/react-core @copilotkit/react-ui\n```" },
  { id: 67, name: "browser-use", full_name: "browser-use/browser-use", owner: "browser-use", description: "AI-powered browser automation. Agents that can navigate, click, type, and extract web data.", stars: 28000, forks: 2900, language: "Python", category: "ai-agents", topics: ["browser-automation", "agents", "web", "selenium"], updated_at: "2026-07-10T08:00:00Z", readme: "## Browser Use\n\nAI-powered browser automation.\n\n### Features\n\n- Natural language commands\n- Click, type, navigate\n- Screenshot and extract\n- Multi-tab support\n- Headless mode\n\n### Quick Start\n\n```bash\npip install browser-use\n```\n\n```python\nfrom browser_use import Agent\nagent = Agent()\nawait agent.run(\"Go to GitHub and search for langchain\")\n```" },
  { id: 68, name: "mastra", full_name: "mastra-ai/mastra", owner: "mastra-ai", description: "TypeScript framework for building AI applications. Agents, RAG, tools, and workflows.", stars: 8200, forks: 350, language: "TypeScript", category: "ai-agents", topics: ["typescript", "agents", "framework", "rag"], updated_at: "2026-07-10T13:00:00Z", readme: "## Mastra\n\nTypeScript framework for AI apps.\n\n### Features\n\n- Agent orchestration\n- RAG pipelines\n- Tool integration\n- Workflow engine\n- Model agnostic\n\n### Quick Start\n\n```bash\nnpm create mastra@latest\n```" },
  { id: 69, name: "llamastack", full_name: "meta-llama/llama-stack", owner: "meta-llama", description: "Meta's Llama Stack — standardized API surface for building Llama-powered AI applications.", stars: 6500, forks: 850, language: "Python", category: "llm-tools", topics: ["llama", "meta", "api", "framework"], updated_at: "2026-07-09T14:00:00Z", readme: "## Llama Stack\n\nStandardized API for Llama models.\n\n### API Endpoints\n\n- Chat Completions\n- Tool Use\n- Agents\n- RAG\n- Batch Inference\n- Safety\n\n### Quick Start\n\n```bash\npip install llama-stack\nllama stack build --template together\n```" },
  { id: 70, name: "instructor", full_name: "jxnl/instructor", owner: "jxnl", description: "Structured outputs for LLMs. Extract typed, validated data from any LLM with function calling.", stars: 14000, forks: 1100, language: "Python", category: "llm-tools", topics: ["structured-output", "pydantic", "extraction", "llm"], updated_at: "2026-07-10T09:00:00Z", readme: "## Instructor\n\nStructured outputs for LLMs.\n\n### Features\n\n- Pydantic model extraction\n- Validation and retry\n- Streaming support\n- Multi-provider (OpenAI, Anthropic, Cohere)\n\n### Quick Start\n\n```python\nfrom pydantic import BaseModel\nfrom instructor import from_openai\n\nclass User(BaseModel):\n    name: str\n    age: int\n\nclient = from_openai(OpenAI())\nuser = client.chat.completions.create(\n    response_model=User,\n    messages=[{\"role\": \"user\", \"content\": \"Extract: John is 25\"}]\n)\n```" },
  { id: 71, name: "goose", full_name: "block/goose", owner: "block", description: "AI agent framework from Block (Square). Type-safe, extensible, with MCP-native architecture.", stars: 8500, forks: 680, language: "Rust", category: "ai-agents", topics: ["agents", "mcp", "framework", "block"], updated_at: "2026-07-09T16:00:00Z", readme: "## Goose\n\nAI agent framework from Block.\n\n### Features\n\n- MCP-native architecture\n- Type-safe agent definitions\n- Extensible tool system\n- Built-in safety guardrails\n\n### Quick Start\n\n```bash\nnpx @block/goose start\n```" },
  { id: 72, name: "vercel-ai-sdk", full_name: "vercel/ai", owner: "vercel", description: "Vercel AI SDK — build AI-powered applications with React, Next.js, and streaming LLM responses.", stars: 15000, forks: 2100, language: "TypeScript", category: "llm-tools", topics: ["ai", "sdk", "streaming", "react", "nextjs"], updated_at: "2026-07-11T05:00:00Z", readme: "## Vercel AI SDK\n\nBuild AI-powered applications.\n\n### Features\n\n- Streaming text and JSON\n- React hooks and components\n- Multi-provider (OpenAI, Anthropic, Google)\n- Tool calling\n- Agent loops\n\n### Quick Start\n\n```bash\nnpm install ai @ai-sdk/openai\n```" },
  { id: 73, name: "lilac", full_name: "lilacai/lilac", owner: "lilacai", description: "Data curation and analysis tool for LLMs. Explore, filter, and clean datasets for training and evaluation.", stars: 3400, forks: 280, language: "Python", category: "data-tools", topics: ["data", "curation", "llm", "analysis", "dataset"], updated_at: "2026-07-08T10:00:00Z", readme: "## Lilac\n\nData curation for LLMs.\n\n### Features\n\n- Dataset exploration\n- Semantic search\n- Duplicate detection\n- PII redaction\n- Quality scoring\n\n### Quick Start\n\n```bash\npip install lilac\nlilac start\n```" },
  { id: 74, name: "argilla", full_name: "argilla-io/argilla", owner: "argilla-io", description: "Open-source platform for data-centric AI. Label, curate, and evaluate data for LLM fine-tuning.", stars: 4500, forks: 480, language: "Python", category: "data-tools", topics: ["data-labeling", "evaluation", "fine-tuning", "platform"], updated_at: "2026-07-09T09:00:00Z", readme: "## Argilla\n\nData-centric AI platform.\n\n### Features\n\n- Data labeling UI\n- Feedback collection\n- Model evaluation\n- Dataset management\n- Active learning\n\n### Quick Start\n\n```bash\npip install argilla\nargilla start\n```" },
  { id: 75, name: "opik", full_name: "comet-ml/opik", owner: "comet-ml", description: "Open-source LLM evaluation platform. Trace, evaluate, and monitor your LLM applications.", stars: 5200, forks: 420, language: "Python", category: "data-tools", topics: ["llm", "evaluation", "monitoring", "observability"], updated_at: "2026-07-10T12:00:00Z", readme: "## Opik\n\nLLM evaluation platform.\n\n### Features\n\n- LLM tracing\n- Evaluation datasets\n- Scoring and metrics\n- Regression detection\n- CI/CD integration\n\n### Quick Start\n\n```bash\npip install opik\n```" },
];

export const REPO_CATEGORIES = [
  { key: "all", label: "All" },
  { key: "ai-agents", label: "AI Agents" },
  { key: "vibe-coding", label: "Vibe Coding" },
  { key: "llm-tools", label: "LLM Tools" },
  { key: "mcp", label: "MCP & Protocols" },
  { key: "workflow", label: "Workflow" },
  { key: "fine-tuning", label: "Fine-tuning" },
  { key: "data-tools", label: "Data & Search" },
  { key: "ui-ux", label: "UI/UX" },
  { key: "learning", label: "Learning" },
  { key: "tools", label: "Dev Tools" },
] as const;

export const AI_SEARCH_QUERIES = [
  "ai agent framework",
  "llm application framework",
  "vibe coding tools",
  "mcp server",
  "rag pipeline",
  "vector database",
  "prompt engineering",
  "llm evaluation",
  "fine-tuning llm",
  "ai coding assistant",
  "embedding model",
  "ai workflow automation",
];
